fix: protect access to currentStep in measurements
When the tour was ended, another measuring happened that caused an unhandled Rejection.

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'this.props.currentStep.tooltipBottomOffset')
```